// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { Preferences } from '@capacitor/preferences';
import { Capacitor } from '@capacitor/core';

const SUPABASE_URL = "https://ouyilgvqbwcekkajrrug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91eWlsZ3ZxYndjZWtrYWpycnVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NzU4MzgsImV4cCI6MjA2MzU1MTgzOH0.HPv36VVU0WpAXidt2ZrjzUSuiNPCMaXk2tI8SryitbE";

// Custom storage adapter for Capacitor mobile apps
const CapacitorStorage = {
  async getItem(key: string): Promise<string | null> {
    if (Capacitor.isNativePlatform()) {
      const { value } = await Preferences.get({ key });
      return value;
    }
    return localStorage.getItem(key);
  },
  async setItem(key: string, value: string): Promise<void> {
    if (Capacitor.isNativePlatform()) {
      await Preferences.set({ key, value });
    } else {
      localStorage.setItem(key, value);
    }
  },
  async removeItem(key: string): Promise<void> {
    if (Capacitor.isNativePlatform()) {
      await Preferences.remove({ key });
    } else {
      localStorage.removeItem(key);
    }
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Configure session persistence for mobile apps
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Enable session persistence across app restarts
    persistSession: true,
    // Use Capacitor secure storage for mobile, localStorage for web
    storage: CapacitorStorage,
    // Auto refresh tokens
    autoRefreshToken: true,
    // Detect session in URL for web
    detectSessionInUrl: false,
    // Flow type for mobile apps
    flowType: 'pkce',
    // Debug mode for troubleshooting
    debug: true
  }
});

// Add debug logging for storage operations
const originalGetItem = CapacitorStorage.getItem;
const originalSetItem = CapacitorStorage.setItem;
const originalRemoveItem = CapacitorStorage.removeItem;

CapacitorStorage.getItem = async (key: string) => {
  const result = await originalGetItem(key);
  console.log(`Storage GET ${key}:`, result ? 'Found' : 'Not found');
  return result;
};

CapacitorStorage.setItem = async (key: string, value: string) => {
  console.log(`Storage SET ${key}:`, value.length, 'characters');
  return await originalSetItem(key, value);
};

CapacitorStorage.removeItem = async (key: string) => {
   console.log(`Storage REMOVE ${key}`);
   return await originalRemoveItem(key);
 };